development:
application_id: 275830165859773
api_key: 275830165859773
secret_key: 43bc9e3a7a14dfe69623c0070a32f600
canvas_page_name: umcp_cssa
callback_url: /art
pretty_errors: true
set_asset_host_to_callback_url: true
tunnel:
public_host_username:
public_host:
public_port: 4007
local_port: 3000
server_alive_interval: 0

production:
application_id: 275830165859773
api_key: 275830165859773
secret_key: 43bc9e3a7a14dfe69623c0070a32f600
canvas_page_name: umcp_cssa
callback_url: http://hollow-waterfall-1839.herokuapp.com/art
pretty_errors: true
set_asset_host_to_callback_url: true
tunnel:
public_host_username:
public_host:
public_port:
local_port:
server_alive_interval: 0

